version: '3'
networks:
  development:
  test:
volumes:
  db_data:
  gem_cache:
  shared_data:
services:
  deal_db:
    image: postgres:12.5-alpine
    container_name: deal_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - shared_data:/var/shared
    networks:
      - development
      - test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5999:5432
  deal_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: deal_app
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - development
    ports:
      - 4250:4250
    stdin_open: true
    tty: true
    env_file: .env.development
    entrypoint: entrypoint.sh
    command: ['rails', 'server', '-p', '4250', '-b', '0.0.0.0']
    environment:
      RAILS_ENV: development
    depends_on:
      - deal_db
  deal_test:
    image: dealbuildr_deal_app
    container_name: deal_test
    volumes:
      - .:/var/app
      - shared_data:/var/shared
      - gem_cache:/usr/local/bundle/gems
    networks:
      - test
    ports:
      - 3001:3000
    stdin_open: true
    tty: true
    env_file: .env.test
    entrypoint: test-entrypoint.sh
    command: ["rails", "-v"]
    environment:
      RAILS_ENV: test
    depends_on:
      - deal_db
      
